apiVersion: policy/v1beta1
kind: PodDisruptionBudget
metadata:
  name: kafka-pdb
  namespace: ops
spec:
  selector:
    matchLabels:
      app: kafka
  maxUnavailable: 1
---  
kind: StatefulSet
apiVersion: apps/v1
metadata:
  name: kafka
  namespace: ops
spec:
  serviceName: kafka-voter
  podManagementPolicy: "Parallel"
  replicas: 3
  selector:
    matchLabels:
      app: kafka
  template:
    metadata:
      labels:
        app: kafka
    spec:         
      terminationGracePeriodSeconds: 300
      containers:
        - name: kafka
          image: repository.anxinyun.cn/devops/fs-kafka:2.13-3.1.0-220402-2
          command:
            - "bash"
            - "-c"
            - "exec ./bin/kafka-server-start.sh ./config/server.properties \
               --override broker.id=${HOSTNAME##*-} \
               --override listeners=PLAINTEXT://:9093 \
               --override zookeeper.connect=zk-cs:2181 "
          ports:
            - name: voter-port
              containerPort: 9093
              protocol: TCP
            - name: plaintext-port
              containerPort: 9092
              protocol: TCP
          env:
          - name: KAFKA_HEAP_OPTS
            value : "-Xmx1G -Xms1G"              
          volumeMounts:
            - name: data-dir
              mountPath: /tmp/
      affinity:
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            - labelSelector:
                matchExpressions:
                  - key: app
                    operator: In
                    values:
                      - kafka
              topologyKey: kubernetes.io/hostname
      nodeSelector:
        kafka: "true"  
      volumes:
        - name: data-dir
          hostPath:
            path: /home/services/kafka/data