kind: StatefulSet
apiVersion: apps/v1
metadata:
  name: kafka
  namespace: ops
spec:
  replicas: 3
  selector:
    matchLabels:
      app: kafka
  template:
    metadata:
      labels:
        app: kafka
    spec:
      containers:
        - name: kafka
          image: repository.anxinyun.cn/devops/kafka:3.1.0
          ports:
            - name: CONTROLLER_PORT
              containerPort: 9093
              protocol: TCP
            - name: PLAINTEXT_PORT
              containerPort: 9092
              protocol: TCP
          env:
            - name: KAFKA_BROKER_ID
              valueFrom:
                fieldRef:
                  apiVersion: v1
                  fieldPath: metadata.name
            - name: PROCESS_ROLES
              value: broker,controller
          envFrom:
            - configMapRef:
                name: cm-kafka
          volumeMounts:
            - name: data_dir
              mountPath: /tmp/
      affinity:
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            - labelSelector:
                matchExpressions:
                  - key: app
                    operator: In
                    values:
                      - kafka
              topologyKey: kubernetes.io/hostname
      hostNetwork: true
      volumes:
        - name: data_dir
          hostPath:
            path: /home/services/kafka/data

